#!/usr/bin/env python3
"""Build script that bundles Python code for Pyodide.

Generates flashy_core.py which can be loaded by Pyodide to set up
the flashy package in the browser's virtual filesystem.
"""

import sys
from pathlib import Path

# Add project root to path
PROJECT_ROOT = Path(__file__).parent.parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

OUTPUT_FILE = Path(__file__).parent / "flashy_core.py"


def read_module(path: Path) -> str:
    """Read a Python module file."""
    return path.read_text()


def build():
    """Bundle core modules into a single file."""
    # Modules to bundle (in dependency order)
    modules = [
        # Core models first (no dependencies)
        ("flashy/core/models.py", "flashy.core.models"),
        # Core modules
        ("flashy/core/problems.py", "flashy.core.problems"),
        ("flashy/core/scoring.py", "flashy.core.scoring"),
        ("flashy/core/number_parser.py", "flashy.core.number_parser"),
        ("flashy/core/i18n.py", "flashy.core.i18n"),
        ("flashy/core/worlds.py", "flashy.core.worlds"),
        ("flashy/core/levels.py", "flashy.core.levels"),
        ("flashy/core/flow.py", "flashy.core.flow"),
        # Game controller
        ("flashy/game.py", "flashy.game"),
        # Web storage
        ("flashy/platforms/web/storage.py", "flashy.platforms.web.storage"),
    ]

    output_lines = [
        '"""Bundled Flashy core modules for Pyodide.',
        "",
        "This file is auto-generated by build.py",
        "Do not edit directly!",
        '"""',
        "",
        "import sys",
        "from types import ModuleType",
        "",
        "# Create package structure",
        "def create_package(name):",
        '    """Create a package and all parent packages."""',
        '    parts = name.split(".")',
        "    for i in range(len(parts)):",
        '        pkg_name = ".".join(parts[:i+1])',
        "        if pkg_name not in sys.modules:",
        "            pkg = ModuleType(pkg_name)",
        "            pkg.__path__ = []",
        "            pkg.__package__ = pkg_name",
        "            sys.modules[pkg_name] = pkg",
        "            # Add to parent",
        "            if i > 0:",
        '                parent_name = ".".join(parts[:i])',
        "                setattr(sys.modules[parent_name], parts[i], pkg)",
        "",
        "# Create all packages",
        'create_package("flashy")',
        'create_package("flashy.core")',
        'create_package("flashy.platforms")',
        'create_package("flashy.platforms.web")',
        'create_package("flashy.storage")',
        "",
    ]

    for rel_path, module_name in modules:
        file_path = PROJECT_ROOT / rel_path
        if not file_path.exists():
            print(f"Warning: {file_path} not found, skipping")
            continue

        code = read_module(file_path)

        output_lines.append(f"# === {module_name} ===")
        output_lines.append("# Create module")
        output_lines.append(f'_mod = ModuleType("{module_name}")')
        package_name = ".".join(module_name.split(".")[:-1])
        output_lines.append(f'_mod.__package__ = "{package_name}"')
        output_lines.append(f'sys.modules["{module_name}"] = _mod')
        # Add to parent package
        parts = module_name.split(".")
        if len(parts) > 1:
            parent = ".".join(parts[:-1])
            attr = parts[-1]
            output_lines.append(f'setattr(sys.modules["{parent}"], "{attr}", _mod)')
        output_lines.append("")
        output_lines.append(f'_code_{module_name.replace(".", "_")} = """\\')

        # Escape the code for embedding
        escaped_code = code.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
        output_lines.append(escaped_code)
        output_lines.append('"""')
        output_lines.append("")
        var_name = f"_code_{module_name.replace('.', '_')}"
        output_lines.append(f'exec({var_name}, sys.modules["{module_name}"].__dict__)')
        output_lines.append("")

    # Write output
    OUTPUT_FILE.write_text("\n".join(output_lines))
    print(f"Generated {OUTPUT_FILE}")
    print(f"Size: {OUTPUT_FILE.stat().st_size / 1024:.1f} KB")


if __name__ == "__main__":
    build()
